project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: ".."
preserve_hierarchy: false
files:
  - source: src/SillyChat/SillyChat/Resource/source/SillyChat_Localizable.json
    translation: src/SillyChat/SillyChat/Resource/translation/%two_letters_code%.json
